//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace HandUpGUI.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IHandUpService", Namespace="http://tempuri.org/")]
    public partial class HandUpService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback JoinTableCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeclineOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddTextToOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPatronToTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallWaiterOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisableEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrantDenyAccessEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMenuItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSubmenuItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback OverrideOrderValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveOrderFromTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReportsOverViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSpecialsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback MenuForProviderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HandUpService() {
            this.Url = global::HandUpGUI.Properties.Settings.Default.HandUpGUI_localhost_HandUpService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event JoinTableCodeCompletedEventHandler JoinTableCodeCompleted;
        
        /// <remarks/>
        public event AddOrderCompletedEventHandler AddOrderCompleted;
        
        /// <remarks/>
        public event ConfirmOrderCompletedEventHandler ConfirmOrderCompleted;
        
        /// <remarks/>
        public event DeclineOrderCompletedEventHandler DeclineOrderCompleted;
        
        /// <remarks/>
        public event AddTextToOrderCompletedEventHandler AddTextToOrderCompleted;
        
        /// <remarks/>
        public event AddTableCompletedEventHandler AddTableCompleted;
        
        /// <remarks/>
        public event AddPatronToTableCompletedEventHandler AddPatronToTableCompleted;
        
        /// <remarks/>
        public event CloseTableCompletedEventHandler CloseTableCompleted;
        
        /// <remarks/>
        public event CallWaiterCompletedEventHandler CallWaiterCompleted;
        
        /// <remarks/>
        public event AddEmployeeCompletedEventHandler AddEmployeeCompleted;
        
        /// <remarks/>
        public event EditEmployeeCompletedEventHandler EditEmployeeCompleted;
        
        /// <remarks/>
        public event DisableEmployeeCompletedEventHandler DisableEmployeeCompleted;
        
        /// <remarks/>
        public event GrantDenyAccessEmployeeCompletedEventHandler GrantDenyAccessEmployeeCompleted;
        
        /// <remarks/>
        public event AddMenuItemCompletedEventHandler AddMenuItemCompleted;
        
        /// <remarks/>
        public event AddSubmenuItemCompletedEventHandler AddSubmenuItemCompleted;
        
        /// <remarks/>
        public event OverrideOrderValueCompletedEventHandler OverrideOrderValueCompleted;
        
        /// <remarks/>
        public event MoveOrderFromTableCompletedEventHandler MoveOrderFromTableCompleted;
        
        /// <remarks/>
        public event ReportsOverViewCompletedEventHandler ReportsOverViewCompleted;
        
        /// <remarks/>
        public event AddSpecialsListCompletedEventHandler AddSpecialsListCompleted;
        
        /// <remarks/>
        public event MenuForProviderCompletedEventHandler MenuForProviderCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet Login([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sUserName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sPassword) {
            object[] results = this.Invoke("Login", new object[] {
                        sUserName,
                        sPassword});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string sUserName, string sPassword) {
            this.LoginAsync(sUserName, sPassword, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string sUserName, string sPassword, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        sUserName,
                        sPassword}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/JoinTableCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet JoinTableCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sTableCode) {
            object[] results = this.Invoke("JoinTableCode", new object[] {
                        sTableCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void JoinTableCodeAsync(string sTableCode) {
            this.JoinTableCodeAsync(sTableCode, null);
        }
        
        /// <remarks/>
        public void JoinTableCodeAsync(string sTableCode, object userState) {
            if ((this.JoinTableCodeOperationCompleted == null)) {
                this.JoinTableCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJoinTableCodeOperationCompleted);
            }
            this.InvokeAsync("JoinTableCode", new object[] {
                        sTableCode}, this.JoinTableCodeOperationCompleted, userState);
        }
        
        private void OnJoinTableCodeOperationCompleted(object arg) {
            if ((this.JoinTableCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JoinTableCodeCompleted(this, new JoinTableCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/AddOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddOrder(int MenuItemID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool MenuItemIDSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TextValue) {
            object[] results = this.Invoke("AddOrder", new object[] {
                        MenuItemID,
                        MenuItemIDSpecified,
                        TextValue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrderAsync(int MenuItemID, bool MenuItemIDSpecified, string TextValue) {
            this.AddOrderAsync(MenuItemID, MenuItemIDSpecified, TextValue, null);
        }
        
        /// <remarks/>
        public void AddOrderAsync(int MenuItemID, bool MenuItemIDSpecified, string TextValue, object userState) {
            if ((this.AddOrderOperationCompleted == null)) {
                this.AddOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrderOperationCompleted);
            }
            this.InvokeAsync("AddOrder", new object[] {
                        MenuItemID,
                        MenuItemIDSpecified,
                        TextValue}, this.AddOrderOperationCompleted, userState);
        }
        
        private void OnAddOrderOperationCompleted(object arg) {
            if ((this.AddOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrderCompleted(this, new AddOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/ConfirmOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConfirmOrder(int OrderID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool OrderIDSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sStatus) {
            object[] results = this.Invoke("ConfirmOrder", new object[] {
                        OrderID,
                        OrderIDSpecified,
                        sStatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmOrderAsync(int OrderID, bool OrderIDSpecified, string sStatus) {
            this.ConfirmOrderAsync(OrderID, OrderIDSpecified, sStatus, null);
        }
        
        /// <remarks/>
        public void ConfirmOrderAsync(int OrderID, bool OrderIDSpecified, string sStatus, object userState) {
            if ((this.ConfirmOrderOperationCompleted == null)) {
                this.ConfirmOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmOrderOperationCompleted);
            }
            this.InvokeAsync("ConfirmOrder", new object[] {
                        OrderID,
                        OrderIDSpecified,
                        sStatus}, this.ConfirmOrderOperationCompleted, userState);
        }
        
        private void OnConfirmOrderOperationCompleted(object arg) {
            if ((this.ConfirmOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmOrderCompleted(this, new ConfirmOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/DeclineOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeclineOrder() {
            object[] results = this.Invoke("DeclineOrder", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeclineOrderAsync() {
            this.DeclineOrderAsync(null);
        }
        
        /// <remarks/>
        public void DeclineOrderAsync(object userState) {
            if ((this.DeclineOrderOperationCompleted == null)) {
                this.DeclineOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeclineOrderOperationCompleted);
            }
            this.InvokeAsync("DeclineOrder", new object[0], this.DeclineOrderOperationCompleted, userState);
        }
        
        private void OnDeclineOrderOperationCompleted(object arg) {
            if ((this.DeclineOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeclineOrderCompleted(this, new DeclineOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/AddTextToOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddTextToOrder() {
            object[] results = this.Invoke("AddTextToOrder", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddTextToOrderAsync() {
            this.AddTextToOrderAsync(null);
        }
        
        /// <remarks/>
        public void AddTextToOrderAsync(object userState) {
            if ((this.AddTextToOrderOperationCompleted == null)) {
                this.AddTextToOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTextToOrderOperationCompleted);
            }
            this.InvokeAsync("AddTextToOrder", new object[0], this.AddTextToOrderOperationCompleted, userState);
        }
        
        private void OnAddTextToOrderOperationCompleted(object arg) {
            if ((this.AddTextToOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTextToOrderCompleted(this, new AddTextToOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/AddTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddTable() {
            object[] results = this.Invoke("AddTable", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddTableAsync() {
            this.AddTableAsync(null);
        }
        
        /// <remarks/>
        public void AddTableAsync(object userState) {
            if ((this.AddTableOperationCompleted == null)) {
                this.AddTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTableOperationCompleted);
            }
            this.InvokeAsync("AddTable", new object[0], this.AddTableOperationCompleted, userState);
        }
        
        private void OnAddTableOperationCompleted(object arg) {
            if ((this.AddTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTableCompleted(this, new AddTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/AddPatronToTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddPatronToTable() {
            object[] results = this.Invoke("AddPatronToTable", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddPatronToTableAsync() {
            this.AddPatronToTableAsync(null);
        }
        
        /// <remarks/>
        public void AddPatronToTableAsync(object userState) {
            if ((this.AddPatronToTableOperationCompleted == null)) {
                this.AddPatronToTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPatronToTableOperationCompleted);
            }
            this.InvokeAsync("AddPatronToTable", new object[0], this.AddPatronToTableOperationCompleted, userState);
        }
        
        private void OnAddPatronToTableOperationCompleted(object arg) {
            if ((this.AddPatronToTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPatronToTableCompleted(this, new AddPatronToTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/CloseTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CloseTable() {
            object[] results = this.Invoke("CloseTable", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CloseTableAsync() {
            this.CloseTableAsync(null);
        }
        
        /// <remarks/>
        public void CloseTableAsync(object userState) {
            if ((this.CloseTableOperationCompleted == null)) {
                this.CloseTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseTableOperationCompleted);
            }
            this.InvokeAsync("CloseTable", new object[0], this.CloseTableOperationCompleted, userState);
        }
        
        private void OnCloseTableOperationCompleted(object arg) {
            if ((this.CloseTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseTableCompleted(this, new CloseTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/CallWaiter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CallWaiter() {
            object[] results = this.Invoke("CallWaiter", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CallWaiterAsync() {
            this.CallWaiterAsync(null);
        }
        
        /// <remarks/>
        public void CallWaiterAsync(object userState) {
            if ((this.CallWaiterOperationCompleted == null)) {
                this.CallWaiterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallWaiterOperationCompleted);
            }
            this.InvokeAsync("CallWaiter", new object[0], this.CallWaiterOperationCompleted, userState);
        }
        
        private void OnCallWaiterOperationCompleted(object arg) {
            if ((this.CallWaiterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallWaiterCompleted(this, new CallWaiterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/AddEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddEmployee() {
            object[] results = this.Invoke("AddEmployee", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddEmployeeAsync() {
            this.AddEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void AddEmployeeAsync(object userState) {
            if ((this.AddEmployeeOperationCompleted == null)) {
                this.AddEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEmployeeOperationCompleted);
            }
            this.InvokeAsync("AddEmployee", new object[0], this.AddEmployeeOperationCompleted, userState);
        }
        
        private void OnAddEmployeeOperationCompleted(object arg) {
            if ((this.AddEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEmployeeCompleted(this, new AddEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/EditEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EditEmployee() {
            object[] results = this.Invoke("EditEmployee", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EditEmployeeAsync() {
            this.EditEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void EditEmployeeAsync(object userState) {
            if ((this.EditEmployeeOperationCompleted == null)) {
                this.EditEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditEmployeeOperationCompleted);
            }
            this.InvokeAsync("EditEmployee", new object[0], this.EditEmployeeOperationCompleted, userState);
        }
        
        private void OnEditEmployeeOperationCompleted(object arg) {
            if ((this.EditEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditEmployeeCompleted(this, new EditEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/DisableEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DisableEmployee() {
            object[] results = this.Invoke("DisableEmployee", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DisableEmployeeAsync() {
            this.DisableEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void DisableEmployeeAsync(object userState) {
            if ((this.DisableEmployeeOperationCompleted == null)) {
                this.DisableEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisableEmployeeOperationCompleted);
            }
            this.InvokeAsync("DisableEmployee", new object[0], this.DisableEmployeeOperationCompleted, userState);
        }
        
        private void OnDisableEmployeeOperationCompleted(object arg) {
            if ((this.DisableEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisableEmployeeCompleted(this, new DisableEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/GrantDenyAccessEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrantDenyAccessEmployee() {
            object[] results = this.Invoke("GrantDenyAccessEmployee", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GrantDenyAccessEmployeeAsync() {
            this.GrantDenyAccessEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void GrantDenyAccessEmployeeAsync(object userState) {
            if ((this.GrantDenyAccessEmployeeOperationCompleted == null)) {
                this.GrantDenyAccessEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrantDenyAccessEmployeeOperationCompleted);
            }
            this.InvokeAsync("GrantDenyAccessEmployee", new object[0], this.GrantDenyAccessEmployeeOperationCompleted, userState);
        }
        
        private void OnGrantDenyAccessEmployeeOperationCompleted(object arg) {
            if ((this.GrantDenyAccessEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrantDenyAccessEmployeeCompleted(this, new GrantDenyAccessEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/AddMenuItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddMenuItem() {
            object[] results = this.Invoke("AddMenuItem", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddMenuItemAsync() {
            this.AddMenuItemAsync(null);
        }
        
        /// <remarks/>
        public void AddMenuItemAsync(object userState) {
            if ((this.AddMenuItemOperationCompleted == null)) {
                this.AddMenuItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMenuItemOperationCompleted);
            }
            this.InvokeAsync("AddMenuItem", new object[0], this.AddMenuItemOperationCompleted, userState);
        }
        
        private void OnAddMenuItemOperationCompleted(object arg) {
            if ((this.AddMenuItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMenuItemCompleted(this, new AddMenuItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/AddSubmenuItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddSubmenuItem() {
            object[] results = this.Invoke("AddSubmenuItem", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddSubmenuItemAsync() {
            this.AddSubmenuItemAsync(null);
        }
        
        /// <remarks/>
        public void AddSubmenuItemAsync(object userState) {
            if ((this.AddSubmenuItemOperationCompleted == null)) {
                this.AddSubmenuItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSubmenuItemOperationCompleted);
            }
            this.InvokeAsync("AddSubmenuItem", new object[0], this.AddSubmenuItemOperationCompleted, userState);
        }
        
        private void OnAddSubmenuItemOperationCompleted(object arg) {
            if ((this.AddSubmenuItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSubmenuItemCompleted(this, new AddSubmenuItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/OverrideOrderValue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OverrideOrderValue() {
            object[] results = this.Invoke("OverrideOrderValue", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OverrideOrderValueAsync() {
            this.OverrideOrderValueAsync(null);
        }
        
        /// <remarks/>
        public void OverrideOrderValueAsync(object userState) {
            if ((this.OverrideOrderValueOperationCompleted == null)) {
                this.OverrideOrderValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOverrideOrderValueOperationCompleted);
            }
            this.InvokeAsync("OverrideOrderValue", new object[0], this.OverrideOrderValueOperationCompleted, userState);
        }
        
        private void OnOverrideOrderValueOperationCompleted(object arg) {
            if ((this.OverrideOrderValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OverrideOrderValueCompleted(this, new OverrideOrderValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/MoveOrderFromTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MoveOrderFromTable() {
            object[] results = this.Invoke("MoveOrderFromTable", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MoveOrderFromTableAsync() {
            this.MoveOrderFromTableAsync(null);
        }
        
        /// <remarks/>
        public void MoveOrderFromTableAsync(object userState) {
            if ((this.MoveOrderFromTableOperationCompleted == null)) {
                this.MoveOrderFromTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveOrderFromTableOperationCompleted);
            }
            this.InvokeAsync("MoveOrderFromTable", new object[0], this.MoveOrderFromTableOperationCompleted, userState);
        }
        
        private void OnMoveOrderFromTableOperationCompleted(object arg) {
            if ((this.MoveOrderFromTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveOrderFromTableCompleted(this, new MoveOrderFromTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/ReportsOverView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReportsOverView() {
            object[] results = this.Invoke("ReportsOverView", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReportsOverViewAsync() {
            this.ReportsOverViewAsync(null);
        }
        
        /// <remarks/>
        public void ReportsOverViewAsync(object userState) {
            if ((this.ReportsOverViewOperationCompleted == null)) {
                this.ReportsOverViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportsOverViewOperationCompleted);
            }
            this.InvokeAsync("ReportsOverView", new object[0], this.ReportsOverViewOperationCompleted, userState);
        }
        
        private void OnReportsOverViewOperationCompleted(object arg) {
            if ((this.ReportsOverViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportsOverViewCompleted(this, new ReportsOverViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/AddSpecialsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddSpecialsList() {
            object[] results = this.Invoke("AddSpecialsList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddSpecialsListAsync() {
            this.AddSpecialsListAsync(null);
        }
        
        /// <remarks/>
        public void AddSpecialsListAsync(object userState) {
            if ((this.AddSpecialsListOperationCompleted == null)) {
                this.AddSpecialsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSpecialsListOperationCompleted);
            }
            this.InvokeAsync("AddSpecialsList", new object[0], this.AddSpecialsListOperationCompleted, userState);
        }
        
        private void OnAddSpecialsListOperationCompleted(object arg) {
            if ((this.AddSpecialsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSpecialsListCompleted(this, new AddSpecialsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/MenuForProvider", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet MenuForProvider([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ProviderID) {
            object[] results = this.Invoke("MenuForProvider", new object[] {
                        ProviderID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MenuForProviderAsync(string ProviderID) {
            this.MenuForProviderAsync(ProviderID, null);
        }
        
        /// <remarks/>
        public void MenuForProviderAsync(string ProviderID, object userState) {
            if ((this.MenuForProviderOperationCompleted == null)) {
                this.MenuForProviderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMenuForProviderOperationCompleted);
            }
            this.InvokeAsync("MenuForProvider", new object[] {
                        ProviderID}, this.MenuForProviderOperationCompleted, userState);
        }
        
        private void OnMenuForProviderOperationCompleted(object arg) {
            if ((this.MenuForProviderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MenuForProviderCompleted(this, new MenuForProviderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHandUpService/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/HandUpWCF")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void JoinTableCodeCompletedEventHandler(object sender, JoinTableCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JoinTableCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JoinTableCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddOrderCompletedEventHandler(object sender, AddOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConfirmOrderCompletedEventHandler(object sender, ConfirmOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeclineOrderCompletedEventHandler(object sender, DeclineOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeclineOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeclineOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddTextToOrderCompletedEventHandler(object sender, AddTextToOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTextToOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTextToOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddTableCompletedEventHandler(object sender, AddTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddPatronToTableCompletedEventHandler(object sender, AddPatronToTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPatronToTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPatronToTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CloseTableCompletedEventHandler(object sender, CloseTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloseTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallWaiterCompletedEventHandler(object sender, CallWaiterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallWaiterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallWaiterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddEmployeeCompletedEventHandler(object sender, AddEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void EditEmployeeCompletedEventHandler(object sender, EditEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DisableEmployeeCompletedEventHandler(object sender, DisableEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisableEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisableEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GrantDenyAccessEmployeeCompletedEventHandler(object sender, GrantDenyAccessEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrantDenyAccessEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GrantDenyAccessEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddMenuItemCompletedEventHandler(object sender, AddMenuItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMenuItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMenuItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddSubmenuItemCompletedEventHandler(object sender, AddSubmenuItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSubmenuItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSubmenuItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void OverrideOrderValueCompletedEventHandler(object sender, OverrideOrderValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OverrideOrderValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OverrideOrderValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MoveOrderFromTableCompletedEventHandler(object sender, MoveOrderFromTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveOrderFromTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MoveOrderFromTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReportsOverViewCompletedEventHandler(object sender, ReportsOverViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportsOverViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReportsOverViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddSpecialsListCompletedEventHandler(object sender, AddSpecialsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSpecialsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSpecialsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MenuForProviderCompletedEventHandler(object sender, MenuForProviderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MenuForProviderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MenuForProviderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591